/*
 * The Side Quest compendium.
 * Each quest is a tiny, real-world adventure.
 *  - category : the filterable theme (see CATEGORIES below)
 *  - rarity   : "common" (default) or "legendary" (drops rarely, feels epic)
 *  - icons    : a little illustrated row
 *  - time / cost / difficulty : the shape of the journey
 */

/* Category definitions: label, glyph, and a tag colour. */
const CATEGORIES = {
  nature: { label: "Nature", icon: "🌿", color: "#5f8f6f" },
  adventure: { label: "Adventure", icon: "🧭", color: "#4f8bad" },
  kindness: { label: "Kindness", icon: "💛", color: "#d99a3a" },
  creativity: { label: "Creativity", icon: "🎨", color: "#8a72c4" },
  social: { label: "Social", icon: "💬", color: "#c56a4a" },
  health: { label: "Health", icon: "🌱", color: "#6aa77f" },
  home: { label: "Home", icon: "🏠", color: "#a9814f" },
  learning: { label: "Learning", icon: "📚", color: "#4a7fb0" },
  mindfulness: { label: "Mindfulness", icon: "🧘", color: "#9b7bc4" },
  fun: { label: "Fun & Silly", icon: "🎲", color: "#d06a9a" },
  food: { label: "Food", icon: "🍎", color: "#c0553f" },
  digital: { label: "Digital Detox", icon: "📵", color: "#6b7a8f" },
  random: { label: "Random", icon: "🎯", color: "#c99a2b" },
};

const QUEST_POOL = [
  /* ---------------- Nature ---------------- */
  {
    id: "tiny-treasures",
    title: "Tiny Treasures",
    category: "nature",
    icons: ["🍂", "🪨", "🪶", "🌼", "🌲"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Collect five tiny treasures from your day — a leaf, a pebble, a feather, a pine cone, a flower. The world leaves gifts for those who pay attention.",
  },
  {
    id: "tree-detective",
    title: "Tree Detective",
    category: "nature",
    icons: ["🌳", "🌲", "🖐️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Meet three different trees. Touch three different species and notice how each one's bark feels.",
  },
  {
    id: "cloud-hunter",
    title: "Cloud Hunter",
    category: "nature",
    icons: ["☁️", "🔭"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Find three interesting cloud shapes drifting overhead and name what each one looks like.",
  },
  {
    id: "rainbow-quest",
    title: "Rainbow Quest",
    category: "nature",
    icons: ["🌈"],
    time: "1 day",
    cost: "Free",
    difficulty: "Medium",
    description:
      "Spot every colour of the rainbow today. Find something — natural or man-made — for each colour.",
  },
  {
    id: "listen-mode",
    title: "Listen Mode",
    category: "nature",
    icons: ["👂", "🌾"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Stand still for two minutes. Count how many different sounds you can hear.",
  },
  {
    id: "leaf-collector",
    title: "Leaf Collector",
    category: "nature",
    icons: ["🍃", "🍁"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Find five different leaf shapes and compare their sizes and colours.",
  },
  {
    id: "nature-photographer",
    title: "Nature Photographer",
    category: "nature",
    icons: ["📷", "🌿"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Take one beautiful photo of nature. No editing allowed.",
  },
  {
    id: "sunset-seeker",
    title: "Sunset Seeker",
    category: "nature",
    icons: ["🌇"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Watch today's sunset. Spend five uninterrupted minutes with the turning of the sky.",
  },
  {
    id: "sky-check",
    title: "Sky Check",
    category: "nature",
    icons: ["🌤️", "⭐"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Look at the sky five times today and notice how it changes.",
  },
  {
    id: "flower-count",
    title: "Flower Count",
    category: "nature",
    icons: ["🌸", "🌼", "🌺"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Spot ten different flowers on your travels.",
  },

  /* ---------------- Adventure / Walking ---------------- */
  {
    id: "long-way-home",
    title: "The Long Way Home",
    category: "adventure",
    icons: ["🛤️", "🧭"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description:
      "Take a different route today. Explore somewhere you have never walked before.",
  },
  {
    id: "treasure-trail",
    title: "Treasure Trail",
    category: "adventure",
    icons: ["👣", "🔍"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Walk until you find something you have never noticed before.",
  },
  {
    id: "bench-break",
    title: "Bench Break",
    category: "adventure",
    icons: ["🪑", "🌳"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Sit on a park bench for five minutes and watch the world go by.",
  },
  {
    id: "hidden-street",
    title: "Hidden Street",
    category: "adventure",
    icons: ["🚶", "🏘️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Walk down a street you have never visited.",
  },
  {
    id: "landmark-hunter",
    title: "Landmark Hunter",
    category: "adventure",
    icons: ["🏛️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Find one interesting building nearby and really look at it.",
  },
  {
    id: "step-bonus",
    title: "Step Bonus",
    category: "adventure",
    icons: ["👟", "➕"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Walk an extra 2,000 steps today.",
  },
  {
    id: "stair-master",
    title: "Stair Master",
    category: "adventure",
    icons: ["🪜"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Choose the stairs instead of the lift every time today.",
  },
  {
    id: "micro-adventure",
    title: "Micro Adventure",
    category: "adventure",
    icons: ["🗺️", "✨"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Spend twenty minutes exploring somewhere nearby.",
  },

  /* ---------------- Kindness ---------------- */
  {
    id: "compliment-quest",
    title: "Compliment Quest",
    category: "kindness",
    icons: ["💬", "😊"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Give three genuine, specific compliments today.",
  },
  {
    id: "hold-the-door",
    title: "Hold the Door",
    category: "kindness",
    icons: ["🚪", "🤗"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Hold a door open for someone and wish them well.",
  },
  {
    id: "thank-you-plus",
    title: "Thank You+",
    category: "kindness",
    icons: ["🙏"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Thank someone who usually goes unnoticed.",
  },
  {
    id: "pay-it-forward",
    title: "Pay It Forward",
    category: "kindness",
    icons: ["🎁", "🤫"],
    time: "20 min",
    cost: "Modest",
    difficulty: "Easy",
    description: "Do one anonymous good deed. Kindness is a currency that never runs dry.",
  },
  {
    id: "check-in",
    title: "Check In",
    category: "kindness",
    icons: ["📱", "💛"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Message someone you have not spoken to in months.",
  },
  {
    id: "smile-chain",
    title: "Smile Chain",
    category: "kindness",
    icons: ["😊", "🔗"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Smile at ten people today and watch the chain spread.",
  },
  {
    id: "nice-review",
    title: "Leave a Nice Review",
    category: "kindness",
    icons: ["⭐", "📝"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Write a positive review for a local business you love.",
  },
  {
    id: "office-hero",
    title: "Office Hero",
    category: "kindness",
    icons: ["🤝", "🦸"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Help a colleague without being asked.",
  },

  /* ---------------- Creativity ---------------- */
  {
    id: "one-minute-sketch",
    title: "One Minute Sketch",
    category: "creativity",
    icons: ["✏️", "⏱️"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Draw something in one minute. Speed silences the inner critic.",
  },
  {
    id: "tiny-poem",
    title: "Tiny Poem",
    category: "creativity",
    icons: ["🖊️", "📜"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Write a four-line poem about your day.",
  },
  {
    id: "photo-challenge",
    title: "Photo Challenge",
    category: "creativity",
    icons: ["📷", "📖"],
    time: "15 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Take a single photo that tells a whole story.",
  },
  {
    id: "doodle-break",
    title: "Doodle Break",
    category: "creativity",
    icons: ["🖍️"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Fill a page with random doodles and let your hand wander.",
  },
  {
    id: "invent-something",
    title: "Invent Something",
    category: "creativity",
    icons: ["💡", "🔧"],
    time: "20 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Come up with a product that does not exist yet.",
  },
  {
    id: "story-starter",
    title: "Story Starter",
    category: "creativity",
    icons: ["📖", "✍️"],
    time: "15 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Write the first paragraph of a story you may never finish.",
  },
  {
    id: "colour-challenge",
    title: "Colour Challenge",
    category: "creativity",
    icons: ["🎨"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Make a drawing using only one colour.",
  },
  {
    id: "object-remix",
    title: "Object Remix",
    category: "creativity",
    icons: ["🔧", "✨"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Find an everyday object and imagine three brand-new uses for it.",
  },

  /* ---------------- Social ---------------- */
  {
    id: "ask-a-question",
    title: "Ask a Question",
    category: "social",
    icons: ["❓", "💬"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Ask someone an interesting question instead of 'How are you?'",
  },
  {
    id: "learn-a-name",
    title: "Learn a Name",
    category: "social",
    icons: ["🤝"],
    time: "15 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Introduce yourself to someone new.",
  },
  {
    id: "memory-lane",
    title: "Memory Lane",
    category: "social",
    icons: ["💭", "🕰️"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Share a favourite memory with someone.",
  },
  {
    id: "family-call",
    title: "Family Call",
    category: "social",
    icons: ["📞", "🫂"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Phone a family member just to chat.",
  },
  {
    id: "lunch-buddy",
    title: "Lunch Buddy",
    category: "social",
    icons: ["🍽️", "👋"],
    time: "1 hr",
    cost: "Modest",
    difficulty: "Easy",
    description: "Eat lunch with someone different today.",
  },
  {
    id: "conversation-champion",
    title: "Conversation Champion",
    category: "social",
    icons: ["💬", "📵"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Avoid checking your phone during one whole conversation.",
  },

  /* ---------------- Health ---------------- */
  {
    id: "water-quest",
    title: "Water Quest",
    category: "health",
    icons: ["💧"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Drink eight glasses of water today.",
  },
  {
    id: "stretch-session",
    title: "Stretch Session",
    category: "health",
    icons: ["🧘", "🤸"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Stretch for ten minutes and let your body unfurl.",
  },
  {
    id: "fresh-air",
    title: "Fresh Air",
    category: "health",
    icons: ["🌬️", "🌳"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Spend twenty minutes outside.",
  },
  {
    id: "screen-break",
    title: "Screen Break",
    category: "health",
    icons: ["📵", "🌿"],
    time: "1 hr",
    cost: "Free",
    difficulty: "Medium",
    description: "Stay away from screens for one hour.",
  },
  {
    id: "early-night",
    title: "Early Night",
    category: "health",
    icons: ["🌙", "😴"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Go to bed thirty minutes earlier than usual.",
  },
  {
    id: "healthy-swap",
    title: "Healthy Swap",
    category: "health",
    icons: ["🍎"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Replace one snack with a piece of fruit.",
  },
  {
    id: "breathe",
    title: "Breathe",
    category: "health",
    icons: ["🫁", "🌬️"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Take ten slow, deep breaths.",
  },
  {
    id: "dance-break",
    title: "Dance Break",
    category: "health",
    icons: ["💃", "🎶"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Dance to one full song like nobody is watching.",
  },

  /* ---------------- Home ---------------- */
  {
    id: "five-minute-tidy",
    title: "Five Minute Tidy",
    category: "home",
    icons: ["🧹", "⏱️"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Set a timer and tidy one room.",
  },
  {
    id: "drawer-rescue",
    title: "Drawer Rescue",
    category: "home",
    icons: ["🗄️"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Organise one drawer that has been calling your name.",
  },
  {
    id: "plant-care",
    title: "Plant Care",
    category: "home",
    icons: ["🪴", "💧"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Water every plant you own.",
  },
  {
    id: "fridge-explorer",
    title: "Fridge Explorer",
    category: "home",
    icons: ["🥘", "🧊"],
    time: "1 hr",
    cost: "Free",
    difficulty: "Medium",
    description: "Cook using only ingredients already at home.",
  },
  {
    id: "declutter-five",
    title: "Declutter Five",
    category: "home",
    icons: ["📦", "♻️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Throw away, recycle, or donate five items.",
  },
  {
    id: "make-bed-plus",
    title: "Make Your Bed+",
    category: "home",
    icons: ["🛏️", "✨"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Make your bed look hotel-worthy.",
  },

  /* ---------------- Learning ---------------- */
  {
    id: "learn-one-thing",
    title: "Learn One Thing",
    category: "learning",
    icons: ["🧠", "💡"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Discover one genuinely interesting fact today.",
  },
  {
    id: "new-word",
    title: "New Word",
    category: "learning",
    icons: ["🔤"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Learn a new word and use it in conversation.",
  },
  {
    id: "language-xp",
    title: "Language XP",
    category: "learning",
    icons: ["🗣️", "🌍"],
    time: "20 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Learn five words in another language.",
  },
  {
    id: "wikipedia-adventure",
    title: "Wikipedia Adventure",
    category: "learning",
    icons: ["📖", "🎲"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Open a random article and read it to the end.",
  },
  {
    id: "podcast-quest",
    title: "Podcast Quest",
    category: "learning",
    icons: ["🎧"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Listen to ten minutes of an educational podcast.",
  },

  /* ---------------- Mindfulness ---------------- */
  {
    id: "silent-minute",
    title: "Silent Minute",
    category: "mindfulness",
    icons: ["🤫", "🧘"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Sit in complete silence for three minutes.",
  },
  {
    id: "gratitude-three",
    title: "Gratitude Three",
    category: "mindfulness",
    icons: ["📝", "🙏"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Write down three things you are grateful for.",
  },
  {
    id: "notice-five",
    title: "Notice Five",
    category: "mindfulness",
    icons: ["👀", "✨"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Find five beautiful things you have never noticed before.",
  },
  {
    id: "phone-free-meal",
    title: "Phone-Free Meal",
    category: "mindfulness",
    icons: ["🍽️", "📵"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Eat one meal with no screens and full attention.",
  },
  {
    id: "slow-walk",
    title: "Slow Walk",
    category: "mindfulness",
    icons: ["🐌", "🌿"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Walk slowly for five minutes and notice everything around you.",
  },

  /* ---------------- Fun & Silly ---------------- */
  {
    id: "duck-counter",
    title: "Duck Counter",
    category: "fun",
    icons: ["🦆"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Count how many ducks you see today.",
  },
  {
    id: "yellow-hunt",
    title: "Yellow Hunt",
    category: "fun",
    icons: ["💛", "🔍"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Find twenty yellow objects.",
  },
  {
    id: "hat-spotter",
    title: "Hat Spotter",
    category: "fun",
    icons: ["🎩", "🧢"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Count how many people you see wearing hats.",
  },
  {
    id: "alphabet-hunt",
    title: "Alphabet Hunt",
    category: "fun",
    icons: ["🔤", "🔍"],
    time: "1 day",
    cost: "Free",
    difficulty: "Hard",
    description:
      "Find something beginning with every letter from A to Z (or as many as you can).",
  },
  {
    id: "coin-finder",
    title: "Coin Finder",
    category: "fun",
    icons: ["🪙"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "See if you can find a lost coin out in the wild.",
  },
  {
    id: "animal-bingo",
    title: "Animal Bingo",
    category: "fun",
    icons: ["🐿️", "🐦", "🐈"],
    time: "1 day",
    cost: "Free",
    difficulty: "Medium",
    description: "Spot five different animals today.",
  },
  {
    id: "funny-sign",
    title: "Funny Sign",
    category: "fun",
    icons: ["📷", "😂"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Photograph the funniest sign you can find.",
  },
  {
    id: "shadow-quest",
    title: "Shadow Quest",
    category: "fun",
    icons: ["🌤️", "👤"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Take a creative photo of your shadow.",
  },
  {
    id: "echo-test",
    title: "Echo Test",
    category: "fun",
    icons: ["🔊"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Find somewhere with an echo and greet it.",
  },

  /* ---------------- Food ---------------- */
  {
    id: "new-taste",
    title: "New Taste",
    category: "food",
    icons: ["🍽️", "✨"],
    time: "20 min",
    cost: "Modest",
    difficulty: "Easy",
    description: "Try something you have never eaten before.",
  },
  {
    id: "rainbow-plate",
    title: "Rainbow Plate",
    category: "food",
    icons: ["🌈", "🥗"],
    time: "1 day",
    cost: "Modest",
    difficulty: "Medium",
    description: "Eat five different coloured fruits or vegetables today.",
  },
  {
    id: "homemade-hero",
    title: "Homemade Hero",
    category: "food",
    icons: ["🍳", "🔥"],
    time: "1 hr",
    cost: "Modest",
    difficulty: "Medium",
    description: "Cook one meal completely from scratch.",
  },
  {
    id: "cafe-explorer",
    title: "Café Explorer",
    category: "food",
    icons: ["☕"],
    time: "30 min",
    cost: "Modest",
    difficulty: "Easy",
    description: "Visit a café you have never been to.",
  },
  {
    id: "slow-bite",
    title: "Slow Bite",
    category: "food",
    icons: ["🍴", "🧘"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Eat one meal slowly, savouring every bite, without distractions.",
  },
  {
    id: "odd-one-out",
    title: "Odd One Out",
    category: "food",
    icons: ["🍈", "🍑"],
    time: "20 min",
    cost: "Modest",
    difficulty: "Easy",
    description: "Buy exactly one piece of fruit you have never tried before.",
  },

  /* ---------------- Digital Detox ---------------- */
  {
    id: "inbox-zero-lite",
    title: "Inbox Zero Lite",
    category: "digital",
    icons: ["📧", "🗑️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Delete or archive fifty old emails.",
  },
  {
    id: "app-cleanup",
    title: "App Cleanup",
    category: "digital",
    icons: ["📱", "🧹"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Delete three apps you never use.",
  },
  {
    id: "wallpaper-refresh",
    title: "Wallpaper Refresh",
    category: "digital",
    icons: ["🖼️", "✨"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Change your phone wallpaper to something inspiring.",
  },
  {
    id: "notification-ninja",
    title: "Notification Ninja",
    category: "digital",
    icons: ["🔕"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Turn off one unnecessary notification for good.",
  },
  {
    id: "unfollow-quest",
    title: "Unfollow Quest",
    category: "digital",
    icons: ["🚫", "📲"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Unfollow ten accounts that do not make you happy.",
  },

  /* ---------------- Random Adventure ---------------- */
  {
    id: "dice-decision",
    title: "Dice Decision",
    category: "random",
    icons: ["🎲"],
    time: "Half a day",
    cost: "Free",
    difficulty: "Medium",
    description: "Let a dice roll decide your afternoon activity.",
  },
  {
    id: "fiver-adventure",
    title: "£5 Adventure",
    category: "random",
    icons: ["💷", "🎉"],
    time: "Half a day",
    cost: "Modest",
    difficulty: "Medium",
    description: "Have as much fun as possible with £5 or less.",
  },
  {
    id: "stranger-recommendation",
    title: "Stranger Recommendation",
    category: "random",
    icons: ["💬", "🎬"],
    time: "15 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Ask someone to recommend a book, film, or café — then follow it up.",
  },
  {
    id: "sunrise-mission",
    title: "Sunrise Mission",
    category: "random",
    icons: ["🌅"],
    time: "1 hr",
    cost: "Free",
    difficulty: "Medium",
    description: "Wake up early enough to watch the sunrise.",
  },
  {
    id: "hidden-gem",
    title: "Hidden Gem",
    category: "random",
    icons: ["📍", "💎"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Find a place within ten minutes of home you have never visited.",
  },
  {
    id: "lucky-number",
    title: "Lucky Number",
    category: "random",
    icons: ["🔢", "🍀"],
    time: "1 day",
    cost: "Free",
    difficulty: "Easy",
    description: "Notice every appearance of your favourite number today.",
  },
  {
    id: "time-capsule",
    title: "Time Capsule",
    category: "random",
    icons: ["⏳", "✉️"],
    time: "20 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Write a note to your future self, seal it, and hide it away.",
  },
  {
    id: "pocket-artist",
    title: "Pocket Artist",
    category: "random",
    icons: ["📓", "✏️"],
    time: "30 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Carry a small notebook and sketch something you see.",
  },
  {
    id: "reverse-routine",
    title: "Reverse Routine",
    category: "random",
    icons: ["🔄"],
    time: "5 min",
    cost: "Free",
    difficulty: "Easy",
    description: "Do one part of your morning routine in a different order.",
  },
  {
    id: "secret-soundtrack",
    title: "Secret Soundtrack",
    category: "random",
    icons: ["🎧", "🎬"],
    time: "10 min",
    cost: "Free",
    difficulty: "Easy",
    description:
      "Walk for ten minutes to music that makes you feel like the main character.",
  },

  /* ================= Legendary (rare drops) ================= */
  {
    id: "legendary-kindness",
    title: "Legendary Kindness",
    category: "kindness",
    rarity: "legendary",
    icons: ["💛", "✨"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Make someone's day — and tell absolutely no one it was you.",
  },
  {
    id: "epic-explorer",
    title: "Epic Explorer",
    category: "adventure",
    rarity: "legendary",
    icons: ["🗺️", "⭐"],
    time: "Half a day",
    cost: "Modest",
    difficulty: "Hard",
    description: "Visit a place you have never been within thirty miles of home.",
  },
  {
    id: "boss-battle-declutter",
    title: "Boss Battle: Declutter",
    category: "home",
    rarity: "legendary",
    icons: ["📦", "⚔️"],
    time: "1 hr",
    cost: "Free",
    difficulty: "Medium",
    description: "Fill one entire bag with items to donate.",
  },
  {
    id: "golden-hour",
    title: "Golden Hour",
    category: "nature",
    rarity: "legendary",
    icons: ["🌅", "🌇"],
    time: "1 day",
    cost: "Free",
    difficulty: "Hard",
    description: "Watch both the sunrise and the sunset on the same day.",
  },
  {
    id: "side-character-upgrade",
    title: "Side Character Upgrade",
    category: "social",
    rarity: "legendary",
    icons: ["🗣️", "⭐"],
    time: "1 day",
    cost: "Free",
    difficulty: "Medium",
    description:
      "Learn the name of someone you see regularly but have never spoken to.",
  },
  {
    id: "nature-master",
    title: "Nature Master",
    category: "nature",
    rarity: "legendary",
    icons: ["🔍", "🐦"],
    time: "Half a day",
    cost: "Free",
    difficulty: "Medium",
    description: "Identify five birds or trees using an identification app.",
  },
  {
    id: "memory-maker",
    title: "Memory Maker",
    category: "creativity",
    rarity: "legendary",
    icons: ["📸", "✨"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Create one photo you will still want to look at in ten years.",
  },
  {
    id: "xp-multiplier",
    title: "XP Multiplier",
    category: "random",
    rarity: "legendary",
    icons: ["⚡", "🎯"],
    time: "1 day",
    cost: "Free",
    difficulty: "Hard",
    description: "Complete three different side quests today.",
  },
  {
    id: "gratitude-scroll",
    title: "The Gratitude Scroll",
    category: "mindfulness",
    rarity: "legendary",
    icons: ["📜", "💌"],
    time: "30 min",
    cost: "Free",
    difficulty: "Medium",
    description: "Write a thank-you letter to someone who changed your life.",
  },
  {
    id: "treasure-hunter",
    title: "Treasure Hunter",
    category: "adventure",
    rarity: "legendary",
    icons: ["🏺", "📷"],
    time: "Half a day",
    cost: "Free",
    difficulty: "Medium",
    description: "Find and photograph something at least a hundred years old.",
  },
];
